version: "3.3"

services:
  mongodb:
    image: mongo:4.2.18
    container_name: mongodb-opencga
    #    ports:
    #      - "27017:27017"
    volumes:
      - ~/opencga-docker-data/mongodb:/data/mongodb
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rs0", "--bind_ip_all", "--dbpath", "/data/mongodb" ]

  solr:
    image: solr:8.8.2
    container_name: solr-opencga
    #    ports:
    #      - "8983:8983"
    volumes:
      - ~/opencga-docker-data/solr:/var/solr/data

  init:
    image: opencb/opencga-base:${project.parent.version}
    depends_on:
      - mongodb
      - solr
    volumes:
      - ./init/init.sh:/opt/opencga/bin/init.sh
      - ./conf/:/opt/opencga/conf/
      - ./init/mongodb-replica-set-init.js:/opt/mongodb/mongodb-replica-set-init.js
    command: [ "/opt/opencga/bin/init.sh" ]

  rest:
    image: opencb/opencga-base:${project.parent.version}
    container_name: rest-opencga
    depends_on:
      - init
    ports:
      - "9090:9090"
    volumes:
      - ./init/rest.sh:/opt/opencga/bin/rest.sh
      - ./conf/:/opt/opencga/conf/
    command: [ "/opt/opencga/bin/rest.sh" ]

  daemon:
    image: opencb/opencga-base:${project.parent.version}
    container_name: daemon-opencga
    depends_on:
      - rest
    volumes:
      - ./init/daemon.sh:/opt/opencga/bin/daemon.sh
      - ./conf/:/opt/opencga/conf/
      - ./data/:/opt/opencga/data/
    command: [ "/opt/opencga/bin/daemon.sh" ]

#  hbase:
#    image: dajobe/hbase