name: Push OpenCGA develop

on:
  push:
    branches:
      - develop
      - release-*
  workflow_dispatch:

jobs:
  build:
    uses: opencb/java-common-libs/.github/workflows/build-java-app-workflow.yml@release-4.7.x
    with:
      maven_opts: -P storage-hadoop,hdp3.1,RClient -Dopencga.war.name=opencga -Dcheckstyle.skip

  test:
    uses: opencb/opencga/.github/workflows/build-test.yml@release-2.7.x
    needs: build
    secrets: inherit

  deploy-maven:
    uses: opencb/java-common-libs/.github/workflows/deploy-maven-repository-workflow.yml@release-4.7.x
    needs: test
    with:
      maven_opts: -P storage-hadoop,hdp3.1 -Dopencga.war.name=opencga
    secrets: inherit

  deploy-docker:
    uses: opencb/java-common-libs/.github/workflows/deploy-docker-hub-workflow.yml@release-4.7.x
    needs: test
    with:
      cli: python3 ./build/cloud/docker/docker-build.py push --images base,init
    secrets: inherit
