name: Long test for run only on weekend
#Every Saturday at 01:10
on:
  schedule:
    - cron: '10 1 * * 6'
    - cron: '40 22 * * 4'

jobs:
  test:
    uses: opencb/opencga/.github/workflows/test-analysis.yml@TASK-3980
    secrets: inherit
    with:
      #test_profile: runLongTests,runMediumTests,runShortTests
      test_profile: runShortTests
      report_context: development