name: "Merge Workflow"

on:
  pull_request:
    branches:
      - "develop"
      - "release-*"
    types:
      - closed

jobs:
  delete-docker:
    uses: opencb/java-common-libs/.github/workflows/delete-docker-hub-workflow.yml@develop
    secrets: inherit


