name: Release new OpenCGA version

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    uses: opencb/java-common-libs/.github/workflows/build-java-app-workflow.yml@develop
    with:
      maven_opts: -P storage-hadoop,hdp3.1,RClient -Dopencga.war.name=opencga -Dcheckstyle.skip

  test:
    uses: opencb/opencga/.github/workflows/build-test.yml@develop
    needs: build
    secrets: inherit


  deploy-maven:
    uses: opencb/java-common-libs/.github/workflows/deploy-maven-repository-workflow.yml@develop
    needs: test
    with:
      maven_opts: -P storage-hadoop,hdp3.1 -Dopencga.war.name=opencga
    secrets: inherit

  deploy-docker:
    uses: opencb/java-common-libs/.github/workflows/deploy-docker-hub-workflow.yml@develop
    needs: test
    with:
      cli: python3 ./build/cloud/docker/docker-build.py push --images base,init
    secrets: inherit

  deploy-docker-ext-tools:
    uses: opencb/java-common-libs/.github/workflows/deploy-docker-hub-workflow.yml@develop
    needs: build
    with:
      cli: python3 ./build/cloud/docker/docker-build.py push --images ext-tools --tag ${{ needs.build.outputs.version }}
    secrets: inherit

  deploy-python:
    uses: opencb/java-common-libs/.github/workflows/deploy-python-workflow.yml@develop
    needs: test
    with:
      cli: ./clients/python/python-build.sh push
      artifact: build-folder
    secrets: inherit

  release:
    uses: opencb/java-common-libs/.github/workflows/release-github-workflow.yml@develop
    needs: test
    with:
      artifact: build-folder
      file: |
        opencga-client-${{ needs.build.outputs.version }}.tar.gz
        clients/R/opencgaR_${{ needs.build.outputs.version }}.tar.gz