name: Release new OpenCGA version

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  test:
    uses: opencb/opencga/.github/workflows/build-test.yml@TASK-2270
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SSH_TESTING_SERVER_HOST: ${{ secrets.SSH_TESTING_SERVER_HOST}}
      SSH_TESTING_SERVER_PORT: ${{ secrets.SSH_TESTING_SERVER_PORT}}
      SSH_TESTING_SERVER_USER: ${{ secrets.SSH_TESTING_SERVER_USER }}
      SSH_TESTING_SERVER_PASSWORD: ${{ secrets.SSH_TESTING_SERVER_PASSWORD }}

  deploy-maven:
    uses: opencb/java-common-libs/.github/workflows/deploy-maven-repository-workflow.yml@develop
    needs: test
    with:
      maven_opts: -P storage-hadoop,hdp3.1 -Dopencga.war.name=opencga
    secrets:
      MAVEN_NEXUS_USER: ${{ secrets.MAVEN_NEXUS_USER }}
      MAVEN_NEXUS_PASSWORD: ${{ secrets.MAVEN_NEXUS_PASSWORD }}
      MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      MAVEN_GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}

  deploy-docker:
    uses: opencb/java-common-libs/.github/workflows/deploy-docker-hub-workflow.yml@develop
    needs: test
    with:
      cli: python3 ./build/cloud/docker/docker-build.py push --images base,init
    secrets:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

  deploy-docker-ext-tools:
    uses: opencb/java-common-libs/.github/workflows/deploy-docker-hub-workflow.yml@develop
    needs: build
    with:
      cli: python3 ./build/cloud/docker/docker-build.py push --images ext-tools --tag ${{ needs.build.outputs.version }}
    secrets:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

  deploy-python:
    uses: opencb/java-common-libs/.github/workflows/deploy-python-workflow.yml@develop
    needs: test
    with:
      cli: ./clients/python/python-build.sh push
      artifact: build-folder
    secrets:
      PYPI_TWINE_USER: ${{ secrets.PYPI_TWINE_USER }}
      PYPI_TWINE_PASSWORD: ${{ secrets.PYPI_TWINE_PASSWORD }}

  release:
    uses: opencb/java-common-libs/.github/workflows/release-github-workflow.yml@develop
    needs: test
    with:
      artifact: build-folder
      file: |
        opencga-client-${{ needs.build.outputs.version }}.tar.gz
        clients/R/opencgaR_${{ needs.build.outputs.version }}.tar.gz