name: Push OpenCGA TASK

on:
  push:
    branches:
      - TASK-*
  workflow_dispatch:

jobs:
  test:
    uses: opencb/opencga/.github/workflows/build-test.yml@TASK-2270
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SSH_TESTING_SERVER_HOST: ${{ secrets.SSH_TESTING_SERVER_HOST}}
      SSH_TESTING_SERVER_PORT: ${{ secrets.SSH_TESTING_SERVER_PORT}}
      SSH_TESTING_SERVER_USER: ${{ secrets.SSH_TESTING_SERVER_USER }}
      SSH_TESTING_SERVER_PASSWORD: ${{ secrets.SSH_TESTING_SERVER_PASSWORD }}

  echo-version:
    needs: test
    #if: contains( ${{ needs.test.build.outputs.version }} , "TASK")
    name: test-version-from-check
    run: echo "Project version is " ${{ needs.test.build.outputs.version }}

#  deploy-docker:
#    uses: opencb/java-common-libs/.github/workflows/deploy-docker-hub-workflow.yml@develop
#    needs: test
#    if: contains( ${{ needs.test.outputs.version }} , "TASK")
#    with:
#      cli: python3 ./build/cloud/docker/docker-build.py push --images base,init --tag ${{ github.ref_name }}
#    secrets:
#      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
#      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}