name: Push OpenCGA TASK

on:
  push:
    branches:
      - TASK-*
  workflow_dispatch:

jobs:
  test:
    uses: opencb/opencga/.github/workflows/build-test.yml@develop
    secrets: inherit
  #  echo-version:
  #    name: check version
  #    runs-on: ubuntu-22.04
  #    needs: test
  #    steps:
  #      - name: Check retrieved value
  #        #if: contains( ${{ needs.test.build.outputs.version }} , "TASK")
  #        run: echo "Project version is " ${{ needs.build.outputs.version }}

  #  deploy-docker:
  #    uses: opencb/java-common-libs/.github/workflows/deploy-docker-hub-workflow.yml@develop
  #    needs: test
  #    if: contains( ${{ needs.test.outputs.version }} , "TASK")
  #    with:
  #      cli: python3 ./build/cloud/docker/docker-build.py push --images base,init --tag ${{ github.ref_name }}
  #    secrets:
  #      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
  #      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

  deploy-docker:
    uses: opencb/java-common-libs/.github/workflows/deploy-docker-hub-workflow.yml@develop
    needs: test
    with:
      cli: python3 ./build/cloud/docker/docker-build.py push --images base,init
    secrets: inherit
#      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
#      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
