name: Push OpenCGA TASK

on:
  push:
    branches:
      - TASK-*
  workflow_dispatch:

jobs:
  build:
    uses: opencb/java-common-libs/.github/workflows/build-java-app-workflow.yml@develop
    with:
      maven_opts: -P storage-hadoop,hdp3.1,RClient -Dopencga.war.name=opencga

  sonar:
    uses: opencb/java-common-libs/.github/workflows/sonar-analysis-workflow.yml@develop
    needs: build
    with:
      sonarProjectKey: opencb_opencga
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  test:
    name: Test OpenCGA
    runs-on: ubuntu-20.04
    needs: build
    strategy:
      matrix:
        mongodb: ["4.2"]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '10'
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
      - name: Start MongoDB v${{ matrix.mongodb }}
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb }}
          mongodb-replica-set: rs-test
      - name: Run Maven Tests
        run: mvn -T 2 clean install -P storage-hadoop,hdp3.1 -DskipTests

  deploy-docker:
    uses: opencb/java-common-libs/.github/workflows/deploy-docker-hub-workflow.yml@develop
    needs: test
    with:
      cli: python3 ./build/cloud/docker/docker-build.py push --images base,init --tag ${{ github.ref_name }}
    secrets:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}