name: LONG TEST ANALYSIS

on:
  push:
    branches:
      - TASK-*

jobs:
  test:
    uses: opencb/opencga/.github/workflows/test-analysis.yml@develop
    secrets: inherit
    with:
      test_profile: runLongTests,runMediumTests,runShortTests
      report_context: development

